import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Nine from "../components/Nine";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Bear Gang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* hero */}
        <section className="">
          <Hero />
          <About />
          <Nine />
        </section>
      </main>
    </div>
  );
}
